x = input('Digite algo:')
print('O tipo primitivo', type(x))
print('Ele é um número?', x.isnumeric())
print('Ele é Alfabético?', x.isalpha())
print('Ele é alfanumérico?', x.isalnum())
print('Ele é só espaço?', x.isspace())
print('Está em maiúsculas ?', x.isupper())
print('Está me minúsculas ?', x.islower())
print('Está capitalizado?', x.istitle())
